from src.main import Main
from .utils.constant import APIURLJSON, APIURLCSV
from .interface import EmpresaExtractInterface,EmpresaLoadInterface,EmpresaAtivaTransformInterface,EmpresaInativaTransformInterface,EmpresaPipelineInterface
from .utils import separatorJson